import uuid
from datetime import datetime

def get_unique_id() -> str:
    """
    returns unique string generated by MD5 hash
    """
    return str(uuid.uuid4())

def get_timestamp() -> int:
    """
    returns UTC timestamp in microseconds
    """
    return int(datetime.now().timestamp() * 1_000_000)


def get_monotonically_increasing_timestamp():
    
    pass

def is_valid_message(message):
    
    return True


def clean_message(message: dict):
    if 'creation_time' in message:
        message['creation_time'] = int(message['creation_time'])
